{
    mode: '%MODE%',
    theme: '%THEME%',
    indentUnit: 4,
    tabSize: 8,
    indentWithTabs: true,
    tabMode: 'shift',
    electricChars: true,
    extraKeys: {
        'Esc': 'toggleFullscreen',
        'Ctrl-Q': function(cm) {codeeditor.foldFunc(cm, cm.getCursor().line);},
        'Cmd-Q': function(cm) {codeeditor.foldFunc(cm, cm.getCursor().line);},
        'Ctrl-I': function(cm) {codeeditor.filebrowser('images')},
        'Cmd-I': function(cm) {codeeditor.filebrowser('images')},
        'Ctrl-L': function(cm) {codeeditor.filebrowser('downloads')},
        'Cmd-L': function(cm) {codeeditor.filebrowser('downloads')},
        'Ctrl-M': function(cm) {codeeditor.filebrowser('media')},
        'Cmd-M': function(cm) {codeeditor.filebrowser('media')},
        'Ctrl-U': function(cm) {codeeditor.filebrowser('userfiles')},
        'Cmd-U': function(cm) {codeeditor.filebrowser('userfiles')},
        'Alt-W': function(cm) {cm.setOption('lineWrapping', !cm.getOption('lineWrapping'))}
    },
    lineWrapping: true,
    lineNumbers: true,
    firstLineNumber: 1,
    matchBrackets: true,
    workTime: 200,
    workDelay: 300,
    onFocus: codeeditor.onFocus,
    undoDepth: 40
}
